/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraswing;

import java.awt.event.KeyEvent;

/**
 *
 * @author lucas
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorCalculadora = new javax.swing.JTextPane();
        botaoCE = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        opDivisao = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        opSubtracao = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        opAdicao = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        opPorcentagem = new javax.swing.JButton();
        opResto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALC");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jScrollPane1.setViewportView(visorCalculadora);

        botaoCE.setBackground(new java.awt.Color(0, 102, 102));
        botaoCE.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        botaoCE.setText("CE");
        botaoCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCEMouseClicked(evt);
            }
        });
        botaoCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCEActionPerformed(evt);
            }
        });

        multiplicar.setBackground(new java.awt.Color(0, 153, 153));
        multiplicar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        multiplicar.setText("*");
        multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicarMouseClicked(evt);
            }
        });

        num7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num7.setText("7");
        num7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num7MouseClicked(evt);
            }
        });
        num7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num7KeyReleased(evt);
            }
        });

        num8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num8.setText("8");
        num8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num8MouseClicked(evt);
            }
        });
        num8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num8KeyReleased(evt);
            }
        });

        num9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num9.setText("9");
        num9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num9MouseClicked(evt);
            }
        });
        num9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num9KeyReleased(evt);
            }
        });

        opDivisao.setBackground(new java.awt.Color(0, 153, 153));
        opDivisao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        opDivisao.setText("/");
        opDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opDivisaoMouseClicked(evt);
            }
        });
        opDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivisaoActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num4.setText("4");
        num4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num4MouseClicked(evt);
            }
        });
        num4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num4KeyReleased(evt);
            }
        });

        num5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num5.setText("5");
        num5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num5MouseClicked(evt);
            }
        });
        num5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num5KeyReleased(evt);
            }
        });

        num6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num6.setText("6");
        num6.setAlignmentY(0.0F);
        num6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num6MouseClicked(evt);
            }
        });
        num6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num6KeyReleased(evt);
            }
        });

        opSubtracao.setBackground(new java.awt.Color(0, 153, 153));
        opSubtracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        opSubtracao.setText("-");
        opSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSubtracaoMouseClicked(evt);
            }
        });

        num1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num1.setText("1");
        num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num1MouseClicked(evt);
            }
        });
        num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num1KeyReleased(evt);
            }
        });

        num2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num2.setText("2");
        num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num2MouseClicked(evt);
            }
        });
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num2KeyReleased(evt);
            }
        });

        num3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num3.setText("3");
        num3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num3MouseClicked(evt);
            }
        });
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        num3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num3KeyReleased(evt);
            }
        });

        opAdicao.setBackground(new java.awt.Color(0, 153, 153));
        opAdicao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        opAdicao.setText("+");
        opAdicao.setAlignmentY(0.0F);
        opAdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opAdicaoMouseClicked(evt);
            }
        });
        opAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAdicaoActionPerformed(evt);
            }
        });

        num0.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        num0.setText("0");
        num0.setMaximumSize(new java.awt.Dimension(50, 23));
        num0.setMinimumSize(new java.awt.Dimension(50, 23));
        num0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num0MouseClicked(evt);
            }
        });
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        num0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num0KeyReleased(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(0, 153, 153));
        resultado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resultado.setText("=");
        resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultadoMouseClicked(evt);
            }
        });
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        resultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultadoKeyReleased(evt);
            }
        });

        opPorcentagem.setBackground(new java.awt.Color(0, 153, 153));
        opPorcentagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        opPorcentagem.setText("%");
        opPorcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opPorcentagemMouseClicked(evt);
            }
        });

        opResto.setBackground(new java.awt.Color(0, 153, 153));
        opResto.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opResto.setText("R");
        opResto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opRestoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opResto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(opPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opResto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCEMouseClicked

    private void multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicarMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "*");
    }//GEN-LAST:event_multiplicarMouseClicked

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        
    }//GEN-LAST:event_num2ActionPerformed

    private void num7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "7");
    }//GEN-LAST:event_num7MouseClicked

    private void num8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "8");
    }//GEN-LAST:event_num8MouseClicked

    private void num9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "9");
    }//GEN-LAST:event_num9MouseClicked

    private void opDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opDivisaoMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "/");
    }//GEN-LAST:event_opDivisaoMouseClicked

    private void num4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "4");
    }//GEN-LAST:event_num4MouseClicked

    private void num5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "5");
    }//GEN-LAST:event_num5MouseClicked

    private void num6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "6");
    }//GEN-LAST:event_num6MouseClicked

    private void opSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSubtracaoMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "-");
    }//GEN-LAST:event_opSubtracaoMouseClicked

    private void num1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "1");
    }//GEN-LAST:event_num1MouseClicked

    private void num2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "2");
    }//GEN-LAST:event_num2MouseClicked

    private void num3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "3");
    }//GEN-LAST:event_num3MouseClicked

    private void opAdicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opAdicaoMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "+");
    }//GEN-LAST:event_opAdicaoMouseClicked

    private void num0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0MouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "0");
    }//GEN-LAST:event_num0MouseClicked

    private void resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultadoMouseClicked
       String valor = visorCalculadora.getText();
        Calculos calculos = new Calculos();
        String resultado = calculos.calculadora(valor);
         
        visorCalculadora.setText(resultado);
    }//GEN-LAST:event_resultadoMouseClicked

    private void opAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAdicaoActionPerformed
        
    }//GEN-LAST:event_opAdicaoActionPerformed

    private void botaoCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCEActionPerformed
        visorCalculadora.setText(" ");
    }//GEN-LAST:event_botaoCEActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
      
    }//GEN-LAST:event_resultadoActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    private void opDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opDivisaoActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num0ActionPerformed

    private void opPorcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opPorcentagemMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "%");        // TODO add your handling code here:
    }//GEN-LAST:event_opPorcentagemMouseClicked

    private void opRestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opRestoMouseClicked
        String valor = visorCalculadora.getText();
        visorCalculadora.setText(valor + "R");        // TODO add your handling code here:
    }//GEN-LAST:event_opRestoMouseClicked

    private void resultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadoKeyReleased
            
    }//GEN-LAST:event_resultadoKeyReleased

    private void resultadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadoKeyPressed
      
    }//GEN-LAST:event_resultadoKeyPressed

    private void num7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num7KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_7){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "7"); 
        }
    }//GEN-LAST:event_num7KeyReleased

    private void num9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num9KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_9){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "9"); 
        }
    }//GEN-LAST:event_num9KeyReleased

    private void num8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num8KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_8){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "8"); 
        }
    }//GEN-LAST:event_num8KeyReleased

    private void num4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num4KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_4){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "4"); 
        }
    }//GEN-LAST:event_num4KeyReleased

    private void num5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num5KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_5){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "5"); 
        }
    }//GEN-LAST:event_num5KeyReleased

    private void num6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num6KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_6){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "6"); 
        }
    }//GEN-LAST:event_num6KeyReleased

    private void num1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num1KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_1){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "1"); 
        }
    }//GEN-LAST:event_num1KeyReleased

    private void num2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num2KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_2){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "2"); 
        }
    }//GEN-LAST:event_num2KeyReleased

    private void num3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num3KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_3){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "3"); 
        }
    }//GEN-LAST:event_num3KeyReleased

    private void num0KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num0KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_0){
            String valor = visorCalculadora.getText();
            visorCalculadora.setText(valor + "0"); 
        }
    }//GEN-LAST:event_num0KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton opAdicao;
    private javax.swing.JButton opDivisao;
    private javax.swing.JButton opPorcentagem;
    private javax.swing.JButton opResto;
    private javax.swing.JButton opSubtracao;
    private javax.swing.JButton resultado;
    private javax.swing.JTextPane visorCalculadora;
    // End of variables declaration//GEN-END:variables
}
